big_library/urls.py
from django.urls import path
from big_library import views

from big_library.apps import BigLibraryConfig

app_name = BigLibraryConfig.name

urlpatterns = [
    path('', views.DocumentListView.as_view(), name='document_list'),
    path('new/', views.DocumentCreateView.as_view(), name='document_create'),
    path('<int:pk>/', views.DocumentDetailView.as_view(), name='document_detail'),
    path('<int:pk>/edit/', views.DocumentUpdateView.as_view(), name='document_update'),
    path('<int:pk>/delete/', views.DocumentDeleteView.as_view(), name='document_delete'),
]

config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(('big_library.urls', 'big_library'), namespace='big_library')),
    path('users/', include(('users.urls', 'users'), namespace='users')),
]

users/urls.py
from django.urls import path
from big_library import views

from users.apps import UsersConfig

app_name = UsersConfig.name

urlpatterns = []

big_library/models.py
from django.db import models
from django.utils import timezone

from django.urls import reverse


class Article(models.Model):
    title = models.CharField(max_length=255, verbose_name='Оглавление')
    description = models.TextField(verbose_name='Описание')
    rubrics = models.CharField(max_length=255, verbose_name='Рубрика')
    created_date = models.DateField(max_length=255, verbose_name='Дата создания', default=timezone.now)
    text = models.TextField(verbose_name='Текст статьи')

    def __str__(self):
        return f'{self.title} {self.rubrics} {self.created_date}'

    def get_absolute_url(self):
        return reverse('document_detail', args=[str(self.id)])

users/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models

# Create your models here.
null_options = {'blank': True, 'null': True}


class User(AbstractUser):
    username = None
    email = models.EmailField(unique=True, verbose_name='почта')

    phone = models.CharField(max_length=35, verbose_name='телефон', **null_options)
    token = models.CharField(max_length=100, verbose_name='токен', **null_options)

    USERNAME_FIELD = "email"
    REQUIRED_FIELDS = []

    class Meta:
        verbose_name = 'Пользователь'
        verbose_name_plural = 'Пользователи'

    def __str__(self):
        return self.email

big_library/forms.py
from django import forms
from django.forms import ModelForm, BooleanField

from big_library.models import Article


class StyleFormMixin:
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            if isinstance(field, BooleanField):
                field.widget.attrs['class'] = "form-check-input"
            else:
                field.widget.attrs['class'] = "form-control"


class DocumentSearchForm(forms.Form):
    query = forms.CharField(label='Поиск', max_length=255)


class ArticleForm(StyleFormMixin, ModelForm):
    class Meta:
        model = Article
        fields = ['rubrics', 'title', 'description', 'text',]

big_library/views.py
from django.views.generic import CreateView, UpdateView, DeleteView, DetailView, ListView
from django.shortcuts import render
from django.urls import reverse_lazy, reverse

from big_library.models import Article
from big_library.documents import ArticleDocument
from big_library.forms import DocumentSearchForm, ArticleForm
from big_library.paginators import CastPaginator


class DocumentListView(ListView):
    model = Article
    paginate_by = 20

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        form = DocumentSearchForm(self.request.GET or None)
        context['form'] = form

        if form.is_valid():
            query = form.cleaned_data['query']
            search_results = ArticleDocument.search().query("multi_match",
                                                            query=query,
                                                            fields=['title', 'description',
                                                                    'text', 'rubrics']).sort('-created_date')

            all_results = search_results.to_queryset()

            paginator = CastPaginator(all_results, self.paginate_by, self.request)
            paginated_results = paginator.paginate()

            print(all_results)
            context['search_results'] = paginated_results
        else:
            context['search_results'] = None
        return context


class DocumentCreateView(CreateView):
    model = Article
    form_class = ArticleForm
    success_url = reverse_lazy('big_library:document_list')


class DocumentUpdateView(UpdateView):
    model = Article
    fields = ['title', 'description', 'text']

    def get_success_url(self):
        return reverse('big_library:document_detail', kwargs={'pk': self.object.pk})


class DocumentDetailView(DetailView):
    model = Article


class DocumentDeleteView(DeleteView):
    model = Article
    success_url = reverse_lazy('big_library:document_list')

users/views.py
from django.shortcuts import render

# Create your views here.

big_library/templates/big_library/article_confirm_delete.html
<!DOCTYPE html>
<html>
<head>
    <title>Удаление статьи</title>
</head>
<body>
    <h1>Удалить "{{ object.title }}"?</h1>

    <form method="post">
        {% csrf_token %}
        <button type="submit">Удалить</button>
        <a href="{{ document.get_absolute_url }}">Отмена</a>
    </form>

    <a href="{% url 'big_library:document_list' %}">На главную</a>
</body>
</html>

big_library/templates/big_library/article_detail.html
<!DOCTYPE html>
<html>
<head>
    <title>{{ object.title }}</title>
</head>
<body>
    <h1>{{ object.title }}</h1>

    <p><strong>Описание:</strong> {{ object.description }}</p>
    <p><strong>Текст статьи:</strong> {{ object.content }}</p>

    <a href="{% url 'big_library:document_update' object.pk %}">Изменить</a> |
    <a href="{% url 'big_library:document_delete' object.pk %}">удалить</a>

    <a href="{% url 'big_library:document_list' %}">На главную</a>
</body>
</html>

big_library/templates/big_library/article_form.html
<!DOCTYPE html>
<html>
<head>
    <title>{% if view.object %}Изменить {% else %}Новый документ {% endif %}</title>
</head>
<body>
    <h1>{% if view.object %}Изменить: {{ view.object.title }}{% else %}Новый документ{% endif %}</h1>

    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        {% if view.object %}
        <button type="submit">Изменить</button>
        {% else %}
        <button type="submit">Сохранить</button>
        {% endif %}
    </form>

    <a href="{% url 'big_library:document_list' %}">На главную</a>
</body>
</html>

big_library/templates/big_library/article_list.html
<!DOCTYPE html>
<html>
<head>
    <title>Библиотека</title>
</head>
<body>
    <h1>Документы</h1>

    <form method="get">
        {{ form.as_p }}
        <button type="submit">Искать</button>
    </form>

    <h2>Результаты:</h2>
    {% if search_results %}
        <ul>
            {% for result in search_results %}
                <li>
                    <p>{{ result.rubrics }}</p>
                    <p>{{ result.created_date }}</p>
                    <a href="{% url 'big_library:document_detail' result.pk %}">{{ result.title }}</a> - {{ result.description }}
                </li>
            {% endfor %}
        </ul>
    {% else %}
        <p>По запросу ничего не найдено.</p>
    {% endif %}

    <!-- Список всех документов -->
    <h2>Все документы:</h2>

    <a href="{% url 'big_library:document_create' %}">Создать документ</a>

    <ul>
        {% for object in object_list %}
            <li>
                <a href="{% url 'big_library:document_detail' object.pk %}" >{{ object.title }}</a> - {{ object.description }}
            </li>
        {% endfor %}
    </ul>

</body>
</html>